// src/components/CarbonForteen.vue
<template>
  <v-container fluid>
    <v-card-text
      class="pa-1"
      style="font-size: 0.75rem; max-width: 350pt; text-align: center; margin: auto; display: block;"
    >
      Interactive radiocarbon dating plot, to show uncertainty in age
      estimation.
      <br />
      Select log or linear time, and drag the sliders below.
    </v-card-text>
    <v-card
      tile
      outlined
      :width="width + 300"
      color="rgba(0,0,0,0.0)"
      style="margin: auto; display: block;"
    >
      <v-row justify="center">
        <v-btn-toggle
          mandatory
          v-model="timeScale"
          rounded
          dense
          style="margin-top:20pt; margin-bottom: -18pt"
        >
          <v-btn
            value="linear"
            x-small
            width="90"
            style="background-color: #f2f0e6"
          >
            Linear Time
          </v-btn>
          <v-btn
            value="log"
            x-small
            width="90"
            style="background-color: #f2f0e6"
          >
            Log Time
          </v-btn>
        </v-btn-toggle>
        <svg id="carbonViz" style="margin: 0 auto;" />
      </v-row>
      <v-row
        justify="center"
        align="center"
        no-gutters
        style="padding-top:10pt"
      >
        <v-col cols="12" sm="3" style="font-size: 0.75rem;">
          Estimated 14C Depletion <br />(per mille, ‰)
        </v-col>
        <v-col cols="8" sm="5" style="transform: scale(0.85)">
          <v-slider
            v-model="inputPerMilDepleted"
            :max="997"
            :min="10"
            color="black"
            hide-details
            dense
            track-color="grey"
            class="align-center"
          >
            <template v-slot:append>
              <v-text-field
                v-model="inputPerMilDepleted"
                hide-details
                class="mt-0 pt-0"
                type="number"
                style="width: 60px; "
              ></v-text-field>
            </template>
          </v-slider>
        </v-col>
      </v-row>
      <v-row justify="center" align="center" no-gutters>
        <v-col cols="12" sm="3" style="font-size: 0.75rem;">
          Standard Deviation of Estimate <br />(per mille, ‰)
        </v-col>
        <v-col cols="8" sm="5" style="transform: scale(0.85)">
          <v-slider
            v-model="standardDeviation"
            :max="25"
            :min="1"
            color="black"
            track-color="grey"
            class="align-center"
          >
            <template v-slot:append>
              <v-text-field
                v-model="standardDeviation"
                class="mt-0 pt-0"
                type="number"
                style="width: 60px"
              ></v-text-field>
            </template>
          </v-slider>
        </v-col>
      </v-row>
      <v-row justify="center" align="center" no-gutters>
        <v-col cols="12" sm="9">
          <v-card-text
            class="pa-2"
            style="font-size: 0.75rem;  text-align: center;"
          >
            Purpose: to experiment with interactively showing estimates
            uncertainty, using radiocarbon dating as an example. Uncertainty is
            shown with a normal distriution on the input, with plus or minus
            three standard deviations (99.7% probability). Made with D3.
            <br />
            <br />
            Note: showing the fraction modern carbon, because it is more
            intuitive to me, but the convention is to use per mille depletion of
            14C.
            <br />
            Also, real laboratory standard deviations are frequently less than 1
            per mille, and are much more accurate than this dashboard initally
            suggests. Eventually I will refine the scales to show much smaller
            errors, which is more realistic, but for now this illustrates the
            concept.
            <br />
            <br />
            (Age calibration with IntCal coming soon...)
          </v-card-text>
        </v-col>
      </v-row>
    </v-card>
  </v-container>
</template>

<script>
import * as d3 from "d3";

const carbon14Calc = (depletion) => {
  return -8033 * Math.log(1 + depletion);
};

const normalDist = (sigma, mean, e) => {
  return (
    (1 / (sigma * Math.sqrt(2 * Math.PI))) *
    Math.exp((-0.5 * (e - mean) ** 2) / sigma ** 2)
  );
};

export default {
  components: {},
  data: () => ({
    margin: {
      top: 20,
      left: 150,
      right: 150,
      bottom: 80,
      xAxis: 30,
      yAxis: 10,
    },
    inputPerMilDepleted: 985,
    standardDeviation: 5,
    height: 300,
    timeScale: "linear",
    transitionDuration: 1000,
    colors: {
      distroLines: "#2f4f87",
      axes: "#4f4f4f", //"##4f4f4f",
      carbonDateLine: "#B22222",
    },
  }),
  mounted() {
    this.instantiateViz();
  },
  computed: {
    estimatedRCAge() {
      return carbon14Calc(-this.inputPerMilDepleted / 1000);
    },
    width() {
      return 400;
      // maybe this if I try to make it work on mobile?
      // if (window.innerWidth > 800) return 550 - this.margin.right;
      // if (window.innerWidth < 700) return 500;
      // return window.innerWidth - 350 - this.margin.right;
    },
    estRadiocarbonDates() {
      let inputdata = [this.inputPerMilDepleted];
      return inputdata.map((e) => ({
        x: carbon14Calc(-e / 1000),
        y: e,
      }));
    },
    distroMax() {
      const mean = this.inputPerMilDepleted;
      const sigma = this.standardDeviation;
      return normalDist(sigma, mean, mean);
    },
    yDistroData() {
      const mean = this.inputPerMilDepleted;
      const sigma = this.standardDeviation;
      let binsStart = this.inputPerMilDepleted - 3 * sigma;
      const binsEnd = this.inputPerMilDepleted + 3 * sigma;
      let bins = [];
      const binSize = (binsEnd - binsStart) / 20;
      while (binsStart < binsEnd) {
        bins.push(binsStart);
        binsStart = binsStart + binSize;
      }
      return bins.map((e) => ({
        bin: e,
        dist: normalDist(sigma, mean, e),
      }));
    },
    xDistroData() {
      function clampDate(depletion) {
        if (depletion >= 998) return 998;
        if (depletion <= 12) return 12;
        return depletion;
      }
      return this.yDistroData.map((e) => ({
        bin: carbon14Calc(-clampDate(e.bin) / 1000),
        dist: e.dist,
      }));
    },
    scales() {
      const xLinear = d3
        .scaleLinear()
        .range([0, this.width])
        .domain([0, 50000]);
      const xLog = d3
        .scaleLog()
        .range([0, this.width])
        .domain([100, 50000]);
      const yScale = d3
        .scaleLinear()
        .range([0, this.height])
        .domain([100, 0]);
      const y2 = d3
        .scaleLinear()
        .range([0, this.height])
        .domain([0, 1000]);
      const ydistrox = d3
        .scaleLinear()
        .range([0, 25])
        .domain([0, this.distroMax]);

      const xdistroy = d3
        .scaleLinear()
        .range([0, 25])
        .domain([this.distroMax, 0]);

      if (this.timeScale === "log")
        return {
          x: xLog,
          y: yScale,
          y2: y2,
          ydistrox: ydistrox,
          xdistroy: xdistroy,
        };
      return {
        x: xLinear,
        y: yScale,
        y2: y2,
        ydistrox: ydistrox,
        xdistroy: xdistroy,
      };
    },
    radiocarbonLineData() {
      let depletion = [
        -0.0125,
        -0.02,
        -0.05,
        -0.07,
        -0.1,
        -0.2,
        -0.3,
        -0.4,
        -0.5,
        -0.6,
        -0.7,
        -0.8,
        -0.9,
        -0.95,
        -0.99,
        -0.998,
      ];
      return depletion.map((e) => ({
        x: carbon14Calc(e),
        y: -e * 1000,
      }));
    },
    carbonLine() {
      return d3
        .line()
        .x((e) => this.scales.x(e.x))
        .y((e) => this.scales.y2(e.y))
        .curve(d3.curveMonotoneX);
    },
    distroLines() {
      const y = d3
        .line()
        .x((e) => this.scales.ydistrox(e.dist))
        .y((e) => this.scales.y2(e.bin))
        .curve(d3.curveMonotoneX);

      const x = d3
        .line()
        .x((e) => this.scales.x(e.bin))
        .y((e) => this.scales.xdistroy(e.dist))
        .curve(d3.curveMonotoneX);
      return { y, x };
    },

    translations() {
      let margin = this.margin;
      const yAxis =
        "translate(" +
        (margin.left - margin.yAxis - 70) +
        "," +
        margin.top +
        ")";
      const yAxis2 =
        "translate(" + (margin.left - margin.yAxis) + "," + margin.top + ")";
      const yAxisTitle =
        "translate(" +
        (margin.left - margin.yAxis - 100) +
        "," +
        (margin.top + this.height / 2) +
        "),rotate(-90)";
      const yAxis2Title =
        "translate(" +
        (margin.left - margin.yAxis - 35) +
        "," +
        (margin.top + this.height / 2) +
        "),rotate(-90)";
      const xAxis =
        "translate(" +
        margin.left +
        "," +
        (margin.top + this.height + margin.xAxis) +
        ")";
      const xAxisDistro =
        "translate(" +
        margin.left +
        "," +
        (margin.top + this.height + margin.xAxis - 25) +
        ")";
      const data = "translate(" + margin.left + "," + margin.top + ")";
      const xAxisTitle =
        "translate(" +
        (margin.left + this.width / 2) +
        "," +
        (margin.top + this.height + margin.xAxis + 40) +
        ")";
      return {
        yAxis,
        yAxis2,
        xAxis,
        yAxisTitle,
        yAxis2Title,
        xAxisDistro,
        data,
        xAxisTitle,
      };
    },
  },
  watch: {
    timeScale(next, prev) {
      if (next && prev) this.updateScales();
    },
    inputPerMilDepleted(next, prev) {
      if (next && prev) this.updateRCEstimate();
    },
    standardDeviation() {
      this.updateRCEstimate();
    },
    estRadiocarbonDates() {
      this.updateRCEstimate();
    },
  },
  methods: {
    instantiateViz: function() {
      // make the svg:
      const svg = d3
        .select("#carbonViz")
        .attr("width", this.width + this.margin.left + this.margin.right)
        .attr("height", this.height + this.margin.top + this.margin.bottom);

      // // ----- axes ----
      svg
        .append("g")
        .call(d3.axisBottom(this.scales.x).ticks(6))
        .attr("transform", this.translations.xAxis)
        .style("color", this.colors.axes)
        .attr("class", "xaxis");
      svg
        .append("text")
        .attr("transform", this.translations.xAxisTitle)
        .style("color", this.colors.axes)
        .style("text-anchor", "middle")
        .text("Radiocarbon Age (years)")
        .style("font-size", 12);

      svg
        .append("g")
        .call(d3.axisLeft(this.scales.y))
        .attr("class", "leftaxis")
        .attr("transform", this.translations.yAxis)
        .style("color", this.colors.axes);

      svg
        .append("text")
        .attr("transform", this.translations.yAxisTitle)
        .style("text-anchor", "middle")
        .style("color", this.colors.axes)
        .text("Fraction Modern Carbon (percent, %)")
        .style("font-size", 12);

      // The other scale for context:
      svg
        .append("g")
        .call(d3.axisLeft(this.scales.y2))
        .attr("class", "leftaxis2")
        .style("color", this.colors.axes)
        .attr("transform", this.translations.yAxis2);
      svg
        .append("text")
        .attr("transform", this.translations.yAxis2Title)
        .style("color", this.colors.axes)
        .style("text-anchor", "middle")
        .text("Depletion (per mille, ‰)")
        .style("font-size", 12);
      // data: the carbon line
      svg
        .append("path")
        .attr("d", this.carbonLine(this.radiocarbonLineData))
        .attr("stroke", this.colors.carbonDateLine)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.data)
        .attr("id", "theline");
      // data: the distro lines:
      svg
        .append("path")
        .attr("d", this.distroLines.y(this.yDistroData))
        .attr("stroke", this.colors.distroLines)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.yAxis2)
        .attr("id", "theydistroline");
      svg
        .append("path")
        .attr("d", this.distroLines.x(this.xDistroData))
        .attr("stroke", this.colors.distroLines)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.xAxisDistro)
        .attr("id", "thexdistroline");
      // just one dot here:
      svg
        .selectAll("thedots")
        .data(this.estRadiocarbonDates)
        .enter()
        .append("circle")
        .attr("cx", (e) => this.scales.x(e.x))
        .attr("cy", (e) => this.scales.y2(e.y))
        .attr("r", 2)
        .style("fill", "black")
        .attr("transform", this.translations.data)
        .attr("id", "thedots");
    },
    updateScales: async function() {
      const svg = d3.select("#carbonViz");
      await svg
        .selectAll(".xaxis")
        .transition()
        .duration(this.transitionDuration)
        .call(
          d3
            .axisBottom(this.scales.x)
            .tickFormat(
              this.timeScale === "log"
                ? (x) => (/[15]/.test(x) ? x : "") // just show 1s and 5s in the ticks
                : d3.format(",.0f")
            )
            .ticks(this.timeScale === "log" ? 10 : 5)
        );
      await d3
        .selectAll("#thedots")
        .data(this.estRadiocarbonDates)
        .transition()
        .duration(this.transitionDuration)
        .attr("cy", (e) => this.scales.y2(e.y))
        .attr("cx", (e) => this.scales.x(e.x))
        .attr("transform", this.translations.data);

      await d3
        .selectAll("#theline")
        .transition()
        .duration(this.transitionDuration)
        .attr("d", this.carbonLine(this.radiocarbonLineData))
        .attr("transform", this.translations.data);

      await d3
        .selectAll("#thexdistroline")
        .transition()
        .duration(this.transitionDuration)
        .attr("d", this.distroLines.x(this.xDistroData))
        .attr("stroke", this.colors.distroLines)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.xAxisDistro);
    },
    updateRCEstimate: async function() {
      await d3
        .selectAll("#thedots")
        .data(this.estRadiocarbonDates)
        .transition()
        .duration(50)
        .attr("cy", (e) => this.scales.y2(e.y))
        .attr("cx", (e) => this.scales.x(e.x))
        .attr("transform", this.translations.data);

      await d3
        .selectAll("#theydistroline")
        .transition()
        .duration(50)
        .attr("d", this.distroLines.y(this.yDistroData))
        .attr("stroke", this.colors.distroLines)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.yAxis2);

      await d3
        .selectAll("#thexdistroline")
        .transition()
        .duration(50)
        .attr("d", this.distroLines.x(this.xDistroData))
        .attr("stroke", this.colors.distroLines)
        .attr("fill", "none")
        .attr("stroke-width", 2)
        .attr("transform", this.translations.xAxisDistro);
    },
  },
};
</script>

// src/components/CarbonForteen.tsx
import { useEffect, useRef, useState, useMemo } from 'react';
import type { ReactNode } from 'react';
import {
  Container,
  Box,
  Typography,
  Slider,
  TextField,
  ToggleButton,
  ToggleButtonGroup,
} from '@mui/material';
import * as d3 from 'd3';
import { BACKGROUND_COLOR } from '../theme';

// Constants
const CHART_CONFIG = {
  width: 400,
  height: 300,
  margin: { top: 20, left: 150, right: 150, bottom: 80, xAxis: 30, yAxis: 10 },
  transitionDuration: { slow: 1000, fast: 50 },
  colors: {
    distroLines: '#2f4f87',
    axes: '#4f4f4f',
    carbonDateLine: '#B22222',
  },
  distroRange: 25,
  distroBins: 20,
  stdDevMultiplier: 3,
};

const SLIDER_STYLES = {
  color: '#666',
  '& .MuiSlider-thumb': { width: 12, height: 12 },
  '& .MuiSlider-track': { height: 2 },
  '& .MuiSlider-rail': { height: 2, opacity: 0.3 },
};

// Utility functions
const carbon14Calc = (depletion: number): number => {
  return -8033 * Math.log(1 + depletion);
};

const normalDist = (sigma: number, mean: number, e: number): number => {
  return (
    (1 / (sigma * Math.sqrt(2 * Math.PI))) *
    Math.exp((-0.5 * (e - mean) ** 2) / sigma ** 2)
  );
};

const clampDate = (depletion: number): number => {
  if (depletion >= 998) return 998;
  if (depletion <= 12) return 12;
  return depletion;
};

// Types
interface DistroDataPoint {
  bin: number;
  dist: number;
}

interface RadiocarbonPoint {
  x: number;
  y: number;
}

interface SliderRowProps {
  label: ReactNode;
  value: number;
  onChange: (value: number) => void;
  min: number;
  max: number;
}

// Components
const SliderRow = ({ label, value, onChange, min, max }: SliderRowProps) => (
  <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', px: 2, py: 1 }}>
    <Typography sx={{ width: '30%', textAlign: 'right', pr: 2 }} component="div" variant="body2">
      {label}
    </Typography>
    <Box sx={{ width: '50%' }}>
      <Slider
        value={value}
        onChange={(_, val) => onChange(val as number)}
        max={max}
        min={min}
        size="small"
        sx={SLIDER_STYLES}
      />
    </Box>
    <Box sx={{ width: '20%', pl: 2 }}>
      <TextField
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        type="number"
        size="small"
        sx={{ width: 70 }}
      />
    </Box>
  </Box>
);

// Helper functions
const createScales = (width: number, height: number, timeScale: 'linear' | 'log', distroMax: number) => {
  const xLinear = d3.scaleLinear().range([0, width]).domain([0, 50000]);
  const xLog = d3.scaleLog().range([0, width]).domain([100, 50000]);
  const yScale = d3.scaleLinear().range([0, height]).domain([100, 0]);
  const y2 = d3.scaleLinear().range([0, height]).domain([0, 1000]);
  const ydistrox = d3.scaleLinear().range([0, CHART_CONFIG.distroRange]).domain([0, distroMax]);
  const xdistroy = d3.scaleLinear().range([0, CHART_CONFIG.distroRange]).domain([distroMax, 0]);

  return {
    x: timeScale === 'log' ? xLog : xLinear,
    y: yScale,
    y2,
    ydistrox,
    xdistroy,
  };
};

const calculateDistributionData = (mean: number, sigma: number) => {
  const binsStart = mean - CHART_CONFIG.stdDevMultiplier * sigma;
  const binsEnd = mean + CHART_CONFIG.stdDevMultiplier * sigma;
  const binSize = (binsEnd - binsStart) / CHART_CONFIG.distroBins;
  
  const bins: number[] = [];
  for (let i = binsStart; i < binsEnd; i += binSize) {
    bins.push(i);
  }
  
  const yData = bins.map((e) => ({
    bin: e,
    dist: normalDist(sigma, mean, e),
  }));

  const xData = yData.map((e) => ({
    bin: carbon14Calc(-clampDate(e.bin) / 1000),
    dist: e.dist,
  }));

  return { yData, xData };
};

function CarbonForteen() {
  const svgRef = useRef<SVGSVGElement>(null);
  const [inputPerMilDepleted, setInputPerMilDepleted] = useState(985);
  const [standardDeviation, setStandardDeviation] = useState(5);
  const [timeScale, setTimeScale] = useState<'linear' | 'log'>('linear');

  const { width, height, margin, transitionDuration, colors } = CHART_CONFIG;

  // Computed values
  const distroMax = useMemo(
    () => normalDist(standardDeviation, inputPerMilDepleted, inputPerMilDepleted),
    [standardDeviation, inputPerMilDepleted]
  );

  const { yData: yDistroData, xData: xDistroData } = useMemo(
    () => calculateDistributionData(inputPerMilDepleted, standardDeviation),
    [inputPerMilDepleted, standardDeviation]
  );

  const estRadiocarbonDates: RadiocarbonPoint[] = useMemo(
    () => [{ x: carbon14Calc(-inputPerMilDepleted / 1000), y: inputPerMilDepleted }],
    [inputPerMilDepleted]
  );

  const scales = useMemo(
    () => createScales(width, height, timeScale, distroMax),
    [timeScale, distroMax, width, height]
  );

  const radiocarbonLineData: RadiocarbonPoint[] = useMemo(() => {
    const depletions = [-0.0125, -0.02, -0.05, -0.07, -0.1, -0.2, -0.3, -0.4, -0.5, -0.6, -0.7, -0.8, -0.9, -0.95, -0.99, -0.998];
    return depletions.map((e) => ({ x: carbon14Calc(e), y: -e * 1000 }));
  }, []);

  const carbonLine = useMemo(() => {
    return d3
      .line<RadiocarbonPoint>()
      .x((e) => scales.x(e.x))
      .y((e) => scales.y2(e.y))
      .curve(d3.curveMonotoneX);
  }, [scales]);

  const distroLines = useMemo(() => {
    const y = d3
      .line<DistroDataPoint>()
      .x((e) => scales.ydistrox(e.dist))
      .y((e) => scales.y2(e.bin))
      .curve(d3.curveMonotoneX);

    const x = d3
      .line<DistroDataPoint>()
      .x((e) => scales.x(e.bin))
      .y((e) => scales.xdistroy(e.dist))
      .curve(d3.curveMonotoneX);

    return { y, x };
  }, [scales]);

  const translations = useMemo(() => {
    const yAxis = `translate(${margin.left - margin.yAxis - 70},${margin.top})`;
    const yAxis2 = `translate(${margin.left - margin.yAxis},${margin.top})`;
    const yAxisTitle = `translate(${margin.left - margin.yAxis - 100},${margin.top + height / 2}),rotate(-90)`;
    const yAxis2Title = `translate(${margin.left - margin.yAxis - 35},${margin.top + height / 2}),rotate(-90)`;
    const xAxis = `translate(${margin.left},${margin.top + height + margin.xAxis})`;
    const xAxisDistro = `translate(${margin.left},${margin.top + height + margin.xAxis - 25})`;
    const data = `translate(${margin.left},${margin.top})`;
    const xAxisTitle = `translate(${margin.left + width / 2},${margin.top + height + margin.xAxis + 40})`;

    return { yAxis, yAxis2, xAxis, yAxisTitle, yAxis2Title, xAxisDistro, data, xAxisTitle };
  }, [margin, width, height]);

  // Initialize visualization
  useEffect(() => {
    if (!svgRef.current) return;

    const svg = d3.select(svgRef.current);
    svg.selectAll('*').remove();

    svg.attr('width', width + margin.left + margin.right).attr('height', height + margin.top + margin.bottom);

    // X-axis
    svg
      .append('g')
      .call(d3.axisBottom(scales.x).ticks(6))
      .attr('transform', translations.xAxis)
      .style('color', colors.axes)
      .attr('class', 'xaxis');

    svg
      .append('text')
      .attr('transform', translations.xAxisTitle)
      .style('color', colors.axes)
      .style('text-anchor', 'middle')
      .text('Radiocarbon Age (years)')
      .style('font-size', 12);

    // Left Y-axis (Fraction Modern Carbon)
    svg
      .append('g')
      .call(d3.axisLeft(scales.y))
      .attr('class', 'leftaxis')
      .attr('transform', translations.yAxis)
      .style('color', colors.axes);

    svg
      .append('text')
      .attr('transform', translations.yAxisTitle)
      .style('text-anchor', 'middle')
      .style('color', colors.axes)
      .text('Fraction Modern Carbon (percent, %)')
      .style('font-size', 12);

    // Right Y-axis (Depletion)
    svg
      .append('g')
      .call(d3.axisLeft(scales.y2))
      .attr('class', 'leftaxis2')
      .style('color', colors.axes)
      .attr('transform', translations.yAxis2);

    svg
      .append('text')
      .attr('transform', translations.yAxis2Title)
      .style('color', colors.axes)
      .style('text-anchor', 'middle')
      .text('Depletion (per mille, ‰)')
      .style('font-size', 12);

    // Carbon line
    svg
      .append('path')
      .attr('d', carbonLine(radiocarbonLineData))
      .attr('stroke', colors.carbonDateLine)
      .attr('fill', 'none')
      .attr('stroke-width', 2)
      .attr('transform', translations.data)
      .attr('id', 'theline');

    // Y distribution line
    svg
      .append('path')
      .attr('d', distroLines.y(yDistroData))
      .attr('stroke', colors.distroLines)
      .attr('fill', 'none')
      .attr('stroke-width', 2)
      .attr('transform', translations.yAxis2)
      .attr('id', 'theydistroline');

    // X distribution line
    svg
      .append('path')
      .attr('d', distroLines.x(xDistroData))
      .attr('stroke', colors.distroLines)
      .attr('fill', 'none')
      .attr('stroke-width', 2)
      .attr('transform', translations.xAxisDistro)
      .attr('id', 'thexdistroline');

    // Data point
    svg
      .selectAll('circle.datapoint')
      .data(estRadiocarbonDates)
      .enter()
      .append('circle')
      .attr('class', 'datapoint')
      .attr('cx', (e) => scales.x(e.x))
      .attr('cy', (e) => scales.y2(e.y))
      .attr('r', 2)
      .style('fill', 'black')
      .attr('transform', translations.data)
      .attr('id', 'thedots');
  }, []);

  // Handle time scale toggle
  const handleTimeScaleChange = (newScale: 'linear' | 'log') => {
    if (!svgRef.current || !newScale) return;
    
    setTimeScale(newScale);
    
    const svg = d3.select(svgRef.current);

    // Calculate scales for the new time scale
    const xLinear = d3.scaleLinear().range([0, width]).domain([0, 50000]);
    const xLog = d3.scaleLog().range([0, width]).domain([100, 50000]);
    const yScale = d3.scaleLinear().range([0, height]).domain([100, 0]);
    const y2 = d3.scaleLinear().range([0, height]).domain([0, 1000]);
    const ydistrox = d3.scaleLinear().range([0, 25]).domain([0, distroMax]);
    const xdistroy = d3.scaleLinear().range([0, 25]).domain([distroMax, 0]);

    const newScales = {
      x: newScale === 'log' ? xLog : xLinear,
      y: yScale,
      y2,
      ydistrox,
      xdistroy,
    };

    svg
      .selectAll('.xaxis')
      .transition()
      .duration(transitionDuration.slow)
      .call(
        d3
          .axisBottom(newScales.x)
          .tickFormat(
            newScale === 'log'
              ? (x) => (/[15]/.test(x.toString()) ? x.toString() : '')
              : d3.format(',.0f')
          )
          .ticks(newScale === 'log' ? 10 : 5) as any
      );

    const carbonLineGenerator = d3
      .line<RadiocarbonPoint>()
      .x((e) => newScales.x(e.x))
      .y((e) => newScales.y2(e.y))
      .curve(d3.curveMonotoneX);

    const xDistroLineGenerator = d3
      .line<DistroDataPoint>()
      .x((e) => newScales.x(e.bin))
      .y((e) => xdistroy(e.dist))
      .curve(d3.curveMonotoneX);

    svg
      .selectAll('#thedots')
      .data(estRadiocarbonDates)
      .transition()
      .duration(transitionDuration.slow)
      .attr('cy', (e) => newScales.y2(e.y))
      .attr('cx', (e) => newScales.x(e.x));

    svg
      .selectAll('#theline')
      .transition()
      .duration(transitionDuration.slow)
      .attr('d', carbonLineGenerator(radiocarbonLineData));

    svg
      .selectAll('#thexdistroline')
      .transition()
      .duration(transitionDuration.slow)
      .attr('d', xDistroLineGenerator(xDistroData));
  };

  // Handle slider input changes
  const handleInputChange = (newInputValue?: number, newStdDevValue?: number) => {
    if (!svgRef.current) return;

    const svg = d3.select(svgRef.current);
    const currentInput = newInputValue ?? inputPerMilDepleted;
    const currentStdDev = newStdDevValue ?? standardDeviation;

    const newEstRadiocarbonDates: RadiocarbonPoint[] = [
      { x: carbon14Calc(-currentInput / 1000), y: currentInput }
    ];

    const { yData: newYDistroData, xData: newXDistroData } = calculateDistributionData(currentInput, currentStdDev);
    const newDistroMax = normalDist(currentStdDev, currentInput, currentInput);
    
    const ydistrox = d3.scaleLinear().range([0, CHART_CONFIG.distroRange]).domain([0, newDistroMax]);
    const xdistroy = d3.scaleLinear().range([0, CHART_CONFIG.distroRange]).domain([newDistroMax, 0]);

    const yDistroLineGenerator = d3
      .line<DistroDataPoint>()
      .x((e) => ydistrox(e.dist))
      .y((e) => scales.y2(e.bin))
      .curve(d3.curveMonotoneX);

    const xDistroLineGenerator = d3
      .line<DistroDataPoint>()
      .x((e) => scales.x(e.bin))
      .y((e) => xdistroy(e.dist))
      .curve(d3.curveMonotoneX);

    svg
      .selectAll('#thedots')
      .data(newEstRadiocarbonDates)
      .transition()
      .duration(transitionDuration.fast)
      .attr('cy', (e) => scales.y2(e.y))
      .attr('cx', (e) => scales.x(e.x));

    svg
      .selectAll('#theydistroline')
      .transition()
      .duration(transitionDuration.fast)
      .attr('d', yDistroLineGenerator(newYDistroData));

    svg
      .selectAll('#thexdistroline')
      .transition()
      .duration(transitionDuration.fast)
      .attr('d', xDistroLineGenerator(newXDistroData));
  };

  // Handler for input per mil depleted changes
  const handleInputPerMilDepletedChange = (newValue: number) => {
    setInputPerMilDepleted(newValue);
    handleInputChange(newValue, undefined);
  };

  // Handler for standard deviation changes
  const handleStandardDeviationChange = (newValue: number) => {
    setStandardDeviation(newValue);
    handleInputChange(undefined, newValue);
  };

  return (
    <Container maxWidth="md">
      <Typography sx={{ textAlign: 'center', maxWidth: '350pt', mx: 'auto', mt: 2 }} variant="body2">
        Interactive radiocarbon dating plot, to show uncertainty in age estimation.
        <br />
        Select log or linear time, and drag the sliders below.
      </Typography>

      <Box
        sx={{
          width: width + 300,
          mx: 'auto',
        }}
      >
        <Box sx={{ display: 'flex', justifyContent: 'center', mt: 2.5, mb: -2 }}>
          <ToggleButtonGroup
            value={timeScale}
            exclusive
            onChange={(_, value) => value && handleTimeScaleChange(value)}
            size="small"
          >
            <ToggleButton value="linear" sx={{ width: 80, backgroundColor: BACKGROUND_COLOR, py: 0.5 }}>
              Linear
            </ToggleButton>
            <ToggleButton value="log" sx={{ width: 80, backgroundColor: BACKGROUND_COLOR, py: 0.5 }}>
              Log
            </ToggleButton>
          </ToggleButtonGroup>
        </Box>

        <Box sx={{ display: 'flex', justifyContent: 'center' }}>
          <svg ref={svgRef} />
        </Box>

        <SliderRow
          label={
            <>
              Estimated 14C Depletion <br />(per mille, ‰)
            </>
          }
          value={inputPerMilDepleted}
          onChange={handleInputPerMilDepletedChange}
          min={10}
          max={997}
        />

        <SliderRow
          label={
            <>
              Standard Deviation of Estimate <br />(per mille, ‰)
            </>
          }
          value={standardDeviation}
          onChange={handleStandardDeviationChange}
          min={1}
          max={25}
        />

        <Box sx={{ px: 4, pb: 2 }}>
          <Typography variant="body2" sx={{ textAlign: 'center' }}>
            Purpose: to experiment with interactively showing estimates uncertainty, using radiocarbon dating as an
            example. Uncertainty is shown with a normal distriution on the input, with plus or minus three standard
            deviations (99.7% probability). Made with D3.
            <br />
            <br />
            Note: showing the fraction modern carbon, because it is more intuitive to me, but the convention is to use
            per mille depletion of 14C.
            <br />
            Also, real laboratory standard deviations are frequently less than 1 per mille, and are much more accurate
            than this dashboard initally suggests. Eventually I will refine the scales to show much smaller errors,
            which is more realistic, but for now this illustrates the concept.
            <br />
            <br />
            (Age calibration with IntCal coming soon...)
          </Typography>
        </Box>
      </Box>
    </Container>
  );
}

export default CarbonForteen;
